# Site settings
title: Bijles Bij Blom | Professioneel en resultaatgericht.
description: "Bijles voor middelbare scholieren."
baseurl: "http://netwerken.github.io/BijlesbijBlom/" # the subpath of your site, e.g. /blog
url: "http://netwerken.github.io/BijlesbijBlom/" # the name of your domain
logo_url: https://cloud.githubusercontent.com/assets/14966904/14042954/2e737d0a-f27f-11e5-9aa2-a2d1e14d46db.jpg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title:
    hero_description: Professioneel en resultaatgericht.

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: 0625263312
    email: Sietseblom@gmail.com
    address: Staringplein, Amsterdam

# Openingstijden
monday_friday: 9:00 – 18:00
saturday: 10:00 – 17:00
sunday: 10:00 – 15:00

# Ervaringen
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Staringplein, Amsterdam
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com/sietse.blom
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:Sietse Blom
feed: yes

# Footer
copyright: Sietse Blom - All rights reserved. Made possible by Orlando Báez from the original Dentist theme and Swiss Jurriëns for tweaking the site.

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
